mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('', include('tournament.urls')),
    path('admin/', admin.site.urls),
]

mysite/tournament/urls.py
from django.urls import path
from . import views
app_name = 'tournament'
urlpatterns = [
    path('', views.base_view, name='base_view'),
    path('login_view', views.login_view, name='login_view'),
    path('home_view', views.home_view, name='home_view'),
    path('register_view', views.register_view, name='register_view'),
    path('logout_view', views.logout_view, name='logout_view'),
    path('create_tournament', views.create_tournament, name='create_tournament'),
    path('create_player', views.create_player, name='create_player'),
    path('my_tournaments', views.tournament_my_table_view, name='my_tournaments'),
    path('tournaments', views.tournament_table_view, name='tournaments'),
    path('tournament/<int:id>', views.tournament_view, name='tournament'),
    path('tournament/<int:id>/delete', views.delete_tournament_view, name='delete'),
    path('tournament/<int:pk>/update', views.update_tournament_view, name='update'),
    path('tournament/<int:id>/<int:pk>/add_player', views.add_player, name='add_player'),
    path('tournament/<int:id>/<int:pk>/delete_player_from_tournament', views.delete_player_from_tournament, name='delete_player_from_tournament'),
]

mysite/tournament/models.py
from email.policy import default
from re import T
from django.db import models
import datetime
from django.contrib.auth.models import User

class MyUser(models.Model):
    email =models.CharField(max_length=30, unique=True)
    name= models.CharField(max_length=30)
    birth_date= models.DateField()

class Tournament(models.Model):
    name= models.CharField(max_length=60, unique=True)
    begin_date= models.DateTimeField()
    end_date= models.DateTimeField(null=True, blank=True)
    max_number_of_player=models.IntegerField()
    creator=models.ForeignKey(User, on_delete=models.DO_NOTHING)


class Player(models.Model):
    name=models.CharField(max_length=50, unique=True)


class PlayersInTournament(models.Model):
    tournament=models.ForeignKey(Tournament, on_delete=models.DO_NOTHING)
    player=models.ForeignKey(Player, on_delete=models.DO_NOTHING)
    class Meta:
        unique_together = ('tournament', 'player',)

mysite/tournament/forms.py
from django import forms
from .models import Tournament, Player
import datetime


class TournamentForm(forms.ModelForm):
    class Meta:
        model=Tournament
        widgets = {
            'begin_date': forms.DateTimeInput(attrs={'type':'datetime-local', 'class':'form-control'},),
            'end_date': forms.DateTimeInput(attrs={'type':'datetime-local', 'class':'form-control'},),
        }
        fields={
            "name",
            "begin_date",
            "max_number_of_player"
        }

class UpdateTournamentForm(forms.ModelForm):
    class Meta:
        model=Tournament
        widgets = {
            'begin_date': forms.DateTimeInput(attrs={'type':'datetime-local', 'class':'form-control'},),
            'end_date': forms.DateTimeInput(attrs={'type':'datetime-local', 'class':'form-control'},),
        }
        exclude=("creator",)

        
    

class PlayerForm(forms.ModelForm):
     class Meta:
        model=Player
        fields={
            "name"
        }

mysite/tournament/views.py
from datetime import datetime
from unicodedata import name
from venv import create
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth import authenticate
from django.shortcuts import render, redirect
from .models import MyUser
from django.contrib.auth.models import User
from .models import Tournament, Player, PlayersInTournament
from .forms import TournamentForm, PlayerForm, UpdateTournamentForm
from django.contrib.auth.decorators import login_required

def format_input_date(date):

    output=[None]*3
    output[0]=int(date[0:4])
    output[1]=int(date[5:7])
    output[2]=int(date[9:10])
    try:
        output.append(int(date[11:13]))
    except:
        pass
    try:
        output.append(int(date[14:16]))
    except:
        pass
    return output

def base_view(request):
    return render(request, 'tournament/base_view.html')
def login_view(request):
    if request.method == "POST":
        password=request.POST.get('password')
        name=request.POST.get('name')
        user = authenticate(request, username=name, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home_view')
        else:
            messages.success(request, ("There Was An Error Logging In, Try Again..."))	
            return redirect('/login_view')
        
    else:
        return render(request, 'tournament/login_view.html', {})	

def home_view(request):
    return render(request, 'tournament/home_view.html')

def register_view(request):
    if request.method == "POST":
        password_=request.POST.get('password')
        email_=request.POST.get('email')
        name_=request.POST.get('name')
        birth_date_=request.POST.get('birth_date')
        if not ( User.objects.filter(username=name).exists() and MyUser.objects.filter(username=name).exists() ):
            try:
                new_user=User.objects.create_user(username=name_, password=password_)
                new_myuser=MyUser.objects.create(email=email_, name=name_, birth_date=birth_date_)
                new_myuser.save()
                messages.info(request, 'You have registered')
                return redirect('/home_view')
            except:
                messages.info(request, 'This name is used, try again')
                return redirect('/home_view')
        else:
            messages.info(request, 'This name is used')
            return redirect('/home_view')

    else:
        return render(request, 'tournament/register_view.html')

@login_required
def logout_view(request):
    logout(request)
    return redirect('/home_view')

@login_required
def create_tournament(request):

    context ={}

    form = TournamentForm(request.POST or None)
    if form.is_valid():
        form.instance.creator=request.user
        form.save() 
        messages.info(request, 'You created a tournament')
        return redirect('/home_view')
         
    context['form']= form
    return render(request, "tournament/create_tournament.html", context)  

@login_required
def create_player(request):
    context={}
    form = PlayerForm(request.POST or None)
    if form.is_valid():
        messages.info(request, 'You created a player')
        form.save()
        return redirect('/home_view')
    context['form']= form
    return render(request, "tournament/create_tournament.html", context)  

@login_required
def tournament_my_table_view(request):
    query_results= Tournament.objects.filter(creator=request.user)
    
    tournaments={
        "tournament":query_results
    }
    return render(request, "tournament/tournament_my_table_view.html", tournaments) 

def tournament_table_view(request):
    tournaments={}
    if request.method == "POST" and request.user.is_authenticated == 1:
        start_date=request.POST.get('start_date')
        end_date_from_post=request.POST.get('end_date')
        try:
            s_date=format_input_date(start_date)
            e_date=format_input_date(end_date_from_post) 
            start = datetime(*s_date)
            end = datetime(*e_date)
            if end>=datetime.now() or  end < start:
                messages.info(request, 'Wrong date input')
                return redirect('/home_view')
        
            query_results= Tournament.objects.filter(begin_date__range=[start, end]).exclude(end_date= None)
            tournaments={
             "tournament":query_results
            } 
        except:
            messages.info(request, 'Wrong date input or none tournaments to show')
    else:
        if request.user.is_authenticated == 0:
            query_results= Tournament.objects.filter(end_date = None).filter(begin_date__lte=datetime.today())
            tournaments={
            "tournament":query_results
         }
    print(tournaments)
    return render(request, "tournament/tournament_table_view.html", tournaments) 

@login_required
def tournament_view(request, id):
    obj = Tournament.objects.get(pk=id)
    query_results=Player.objects.filter()
    player_in_tournamets= PlayersInTournament.objects.filter(tournament=obj)
    
    result={
        "tournament":obj,
        "player":query_results,
        "player_in_tournamets":player_in_tournamets
    }

    return render(request, "tournament/tournament_view.html", result)

@login_required
def delete_tournament_view(request, id):
    context ={}
    obj = get_object_or_404(Tournament, id = id)
    if request.method =="POST":
        obj.delete()
        return redirect('/home_view')

@login_required
def update_tournament_view(request, pk):
    obj = Tournament.objects.get(id = pk)
    form = UpdateTournamentForm(instance=obj)
    if request.method =="GET":
        form = UpdateTournamentForm(request.GET, instance=obj)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            url = "/tournament/"+str(pk)
            return redirect(url)
    context = {"form":form}
    return render(request, "tournament/update_view.html", context)

@login_required
def add_player(request, pk, id):
    x = Tournament.objects.get(id = id)
    y = Player.objects.get(id = pk)
    obj=PlayersInTournament(tournament = x , player = y)
    player_in_tournamets= PlayersInTournament.objects.filter(tournament=x)
    print(x.max_number_of_player)
    print( player_in_tournamets.count())
    print(x.max_number_of_player >= player_in_tournamets.count())
    if x.max_number_of_player > player_in_tournamets.count() and x.end_date == None:
        try:
            obj.save()
        except:
            messages.info(request, 'This players in already in this tournament')
        url = "/tournament/"+str(id)
        return redirect(url)
    else:
        messages.info(request, 'This tournament has enough players or this tournaments is over')
        url = "/tournament/"+str(id)
        return redirect(url)

@login_required  
def delete_player_from_tournament(request, pk, id):

    obj=PlayersInTournament.objects.get(tournament = id , player = pk)
    if request.method =="POST":
        obj.delete()
        url = "/tournament/"+str(id)
        return redirect(url)

mysite/tournament/templates/tournament/base_view.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'tournament/style.css' %}" >
<style>
body {margin:20px;}

.button {
    border: none;
    color: black;
    margin: 10px;
    padding: 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    cursor: pointer;
    float: rigth;
    overflow:hidden;
    position: absolute;
    right: 10px;
    top: 5px;
    background-color: white;
  }
.button:hover{
    background-color: #aaf7eb;
}

ul {
  list-style-type: none;
  overflow: hidden;
  background-color: #ffffff;
  position: fixed;
  width: 100%;
}

li {
  float: left;
}

li a {
  display: block;
  color: black;
  text-align: right;
  padding: 14px 16px;
  text-decoration: none;
  background-color: #ffffff;
}

li a:hover:not(.active) {
  background-color: #aaf7eb;
}

.active {
  background-color: #aaf7eb;
}
* {
  box-sizing: border-box;
}

.column {
  display: table;
  float: left;
  padding: 10px;
  height: 400px;
  width: 600px;

}
.row {
  display: table;
  height: 100px;
  width: 1200px;

}

</style>
</head>
<body style="background-color:white;">

<div class="row">
    {% block nav %}
        <ul id="nav">
            <li>{% block nav-home_view %} <a href="{% url 'tournament:home_view' %}">Home</a>{% endblock %}</li>
            {% if request.user.is_authenticated == 0 %}
            <li>{% block nav-login_view %} <a href="{% url 'tournament:login_view' %}">Login</a>{% endblock %}</li> 
            <li>{% block nav-register_view %} <a href="{% url 'tournament:register_view' %}">Register</a>{% endblock %}</li>
            <li>{% block nav-tournament_table_view %} <a href="{% url 'tournament:tournaments' %}">Current Tournaments</a>{% endblock %}</li>
            {% endif%}
            {% if request.user.is_authenticated == 1 %}
            <li>{% block nav-create_tournament %} <a href="{% url 'tournament:create_tournament' %}">Create New Tournament</a>{% endblock %}</li>
            <li>{% block nav-create_player %} <a href="{% url 'tournament:create_player' %}">Create New Player</a>{% endblock %}</li>
            <li>{% block nav-tournament_my_table_view %} <a href="{% url 'tournament:my_tournaments' %}">My Tournaments</a>{% endblock %}</li>
            <li>{% block nav-user_tournament_table_view %} <a href="{% url 'tournament:tournaments' %}">Search Past Tournaments</a>{% endblock %}</li>
            <li>{% block nav-logout %} <a href="{% url 'tournament:logout_view' %}">Logout</a>{% endblock %}</li>
            {% endif%}
        </ul>
        

      {% endblock %}
</div>


     
<div class="row" >
        {% block page_detail%}
        {% endblock %}
</div>
  
<div class="row">
  {% if messages %}
    {% for message in messages %}
        {{message}}
    {% endfor %}
  {% endif %}
</div>  

</body>
</html>

mysite/tournament/templates/tournament/create_tournament.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>

<form method="POST" enctype="multipart/form-data">
 
  {% csrf_token %}
  {{ form.as_p }}
   
  <input type="submit" value="Create">
</form>
{% endblock %}

mysite/tournament/templates/tournament/home_view.html
{% extends "tournament/base_view.html" %}
{% block  page_detail %}<strong class="nav-active"></strong>

    <h2>Welcome to tournaments!</h1>
    {% if request.user.is_authenticated == 0 %}
    <p>To see ongoing tournaments clik Tournaments tab</p>
    {% endif%}
    {% if request.user.is_authenticated == 1 %}
    <p>You can manage a tournament by choosing it in Tournaments tab</p>
    {% endif%}
  
{% endblock %}  

mysite/tournament/templates/tournament/login_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>

<form method = "post">{% csrf_token %}
  <label for="name">Name:</label><br>
  <input type="text" id="name" name="name" ><br>
  <label for="password">Password:</label><br>
  <input type="password" id="password" name="password"><br><br>
  <input type="submit" value="Login">
</form>
  
{% endblock %}

mysite/tournament/templates/tournament/register_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>

  <form method = "post">{% csrf_token %}
    <label for="email">Email:</label><br>
    <input type="text" id="email" name="email" ><br>
    <label for="name">Name:</label><br>
    <input type="text" id="name" name="name" ><br>
    <label for="birth_date">Birth date:</label><br>
    <input type="date" id="birth_date" name="birth_date" ><br>
    <label for="password">Password:</label><br>
    <input type="password" id="password" name="password"><br><br>
    <input type="submit" value="Register">
  </form>

{% endblock %}

mysite/tournament/templates/tournament/tournament_my_table_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
</style>


<table>
  <tr> 
    <th> Name </th>
    <th> Begin date </th>
    <th> End date </th>
    <th> Maximum number of players </th>
</tr>
    {% for item in tournament %}
    <tr> 
        <td> <a href="{% url 'tournament:tournament' item.id %}"> {{ item.name }} </a> </td>
        <td>{{ item.begin_date }}</td>
        <td>{{ item.end_date }}</td>
        <td>{{ item.max_number_of_player }}</td>
       </tr>
    {% endfor %}
</table>

{% endblock %}

mysite/tournament/templates/tournament/tournament_table_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
      }
      
      td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
      }
      
      tr:nth-child(even) {
        background-color: #dddddd;
      }
  </style>

{% if request.user.is_authenticated == 1 %}
    <p> Input dates and see the tournaments </p>
    <form method = "post">{% csrf_token %}
    <label for="start_date">Start date:</label><br>
    <input type="datetime-local" id="start_date" name="start_date" ><br>
    <label for="start_date">End date:</label><br>
    <input type="datetime-local" id="end_date" name="end_date"  ><br>
    <input type="submit" value="Search">
    </form>
{% endif %}
<br></br>
<table>
    <tr> 
        <th> Name </th>
        <th> Begin date </th>
        <th> End date </th>
        <th> Maximum number of players </th>
    </tr>
    {% for item in tournament %}
    <tr> 
        <td>  {{ item.name }} </td>
        <td>{{ item.begin_date }}</td>
        <td>{{ item.end_date }}</td>
        <td>{{ item.max_number_of_player }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

mysite/tournament/templates/tournament/tournament_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>


<style>
    .button1 {
        border: none;
        color: black;
        margin-left: 40px;
        padding: 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        cursor: pointer;
        float: rigth;
        overflow:hidden;
        position: relative;
        background-color: white;
      }
    .button1:hover{
        background-color: #aaf7eb;
    }

</style>

    <div class="column">
        <h2> Details of tournament </h2>
        <p>Name: {{tournament.name}} </p>
        <p>Begin date: {{ tournament.begin_date }} </p>
        <p>End date: {{ tournament.end_date }} </p>
        <p>Maximum number of players: {{ tournament.max_number_of_player }}</p>
        
        <h3> Players in this tournament</h3>
        <table>
            {% for x in player_in_tournamets %}
                <tr> 
                    <td>{{ x.player.name }} </td> 
                    <td><form action="{{tournament.id}}/{{x.player.id}}/delete_player_from_tournament" method="POST">
                        {% csrf_token %}
                        <button class="mm-button mm-small mm-circle">-</button> 
                    </form></td> 
                </tr>
            {% endfor %}
        </table>

        <br></br>
        <form action="{{tournament.id}}/delete" method="POST">
            {% csrf_token %}
            <button class="button1" value="1" name="delete_button">Delete this tournament</button>
        </form> 
        <form action="{{tournament.id}}/update" method="POST">
            {% csrf_token %}
            <button class="button1" value="1" name="update_button">Update this tournament</button>
        </form> 
    </div>

    <div class="column">
        <h3> Choose players for this tournament</h3>
        <table>
            {% for p in player %}
            <tr> 
                <td>{{ p.name }}  </td>
                <td>
                    <form action="{{tournament.id}}/{{p.id}}/add_player" method="POST">
                        {% csrf_token %}
                        <button class="mm-button mm-small mm-circle">+</button> 
                    </form>
                   
                </td>
            </tr>
            {% endfor %}
        </table>    
        

    </div>



{% endblock %}

mysite/tournament/templates/tournament/update_view.html
{% extends "tournament/base_view.html" %}
{% block page_detail%}<strong class="nav-active"></strong>
<style>
   
    form {
      margin-left: 50px;
    }
</style>
    
    <form  method="GET">   
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form> 

{{form.errors}}
{% endblock %}